[package]
name = "fast-clock"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["m-mueller678"]
description = "Low-overhead timing without hiding the details from you"
repository = "https://github.com/m-mueller678/fast-clock"
readme = "readme.md"
categories = ["development-tools::profiling","hardware-support","no-std::no-alloc"]
keywords = ["timing","clock","tsc","nanosecond-timing"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]

[dependencies]

[features]
default = ["fast-clock","std"]
fast-clock = ["x86_64-tsc","aarch64-generic-timer"]
fast-clock-aarch64-56bit = ["fast-clock"]
x86_64-tsc=[]
aarch64-generic-timer=[]
std=[]
